export const theme = {
  colors: {
    white: '#FFFFFF',
    grayBackground: '#F5F5F5',
    gray01: '#E0E0E0',
    gray02: '#BDBDBD',
    gray03: '#9E9E9E',
    gray04: '#6D6D6D',
    gray05: '#4B4B4B',
    gray06: '#2B2B2B',
    primary: '#6639DF',
    primary10: '#F0EBFC',
    primary20: '#E0D7F9',
    primary60: '#A388EC',
    primary80: '#8561E5',
    accent: '#CEF763',
    lightAccent: '#F4FFBE',
    darkAccent: '#BAD84F',
    error: '#FF5A5A',
    lightError: '#FFB3B3',
    gradient: {
      start: '#472998',
      end: '#19132A',
    },
    scrollableBlur: {
      start: '#4B4B4B',
      end: '#19132A',
    },
    uploadBox: {
      active: '#F0EBFCB3',
      default: '#F0EBFC66',
    },
    overlay: '#000000B3',
    kakaoTalk: '#FFEB00',
    naver: '#03C75A',
  },
  typography: {
    header01: {
      fontWeight: 700,
      fontSize: '28px',
      lineHeight: '130%',
    },
    header02: {
      fontWeight: 600,
      fontSize: '22px',
      lineHeight: '140%',
    },
    header03: {
      fontWeight: 600,
      fontSize: '18px',
      lineHeight: '140%',
    },
    bodyLarge: {
      fontWeight: 500,
      fontSize: '16px',
      lineHeight: '150%',
    },
    bodyRegular: {
      fontWeight: 400,
      fontSize: '16px',
      lineHeight: '160%',
    },
    captionSmall: {
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '160%',
    },
    buttonPrimary: {
      fontWeight: 600,
      fontSize: '16px',
      lineHeight: '120%',
    },
    buttonSecondary: {
      fontWeight: 600,
      fontSize: '14px',
      lineHeight: '120%',
    },
    buttonTertiary: {
      fontWeight: 500,
      fontSize: '12px',
      lineHeight: '120%',
    },
  },
  zIndex: {
    overlayIcon: 1,
    imageGrid: 2,
    text: 3,
    scrollableArea: 3,
    topActionButton: 4,
    loadingSpinner: 5,
    overlay: 100,
    floatingActionButton: 400,
    toast: 500,
  },
  layout: {
    width: '400px',
    padding: {
      topBottom: '32px',
      leftRight: '16px',
    },
  },
  breakpoints: {
    desktop: '',
    mobile: '375px',
  },
};
